FROM public.ecr.aws/lambda/python:3.12

COPY src/career_scraper ${LAMBDA_TASK_ROOT}/career_scraper

RUN pip install --no-cache-dir --target ${LAMBDA_TASK_ROOT} \
    fastapi mangum boto3

CMD ["career_scraper.lambda_handler.handler"]
